from __future__ import annotations

import math
from typing import Any, Protocol

from pydantic import BaseModel, Field


class VectorStoreRecord(BaseModel):
    """
    A chunk record that can be stored in a vector store.

    In production this will map to a database row in PostgreSQL/pgvector.
    """

    chunk_id: str
    document_id: str
    content: str
    embedding: list[float] | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class VectorStoreQuery(BaseModel):
    """
    Query object for vector search.

    For now, the query_embedding must be generated by the embedding provider
    before calling the vector store.
    """

    query: str
    embedding: list[float] | None = None
    top_k: int = Field(default=5, ge=1, le=20)


class VectorStoreSearchResult(BaseModel):
    """
    A search result with a similarity score.
    """

    chunk_id: str
    document_id: str
    content: str
    score: float
    metadata: dict[str, Any] = Field(default_factory=dict)


class VectorStore(Protocol):
    async def upsert_chunks(self, records: list[VectorStoreRecord]) -> None:
        """Persist chunks and embeddings."""

    async def search(self, query: VectorStoreQuery) -> list[VectorStoreSearchResult]:
        """Search vector-backed chunks."""


class InMemoryVectorStore:
    """
    Simple in-memory vector store for learning and local development.

    This is not persistent.
    If the backend restarts, all records are lost.

    It is useful before implementing PostgreSQL/pgvector.
    """

    def __init__(self) -> None:
        self._records: dict[str, VectorStoreRecord] = {}

    async def upsert_chunks(self, records: list[VectorStoreRecord]) -> None:
        for record in records:
            if record.embedding is None:
                raise ValueError(f"Record {record.chunk_id} has no embedding.")

            self._records[record.chunk_id] = record

    async def search(self, query: VectorStoreQuery) -> list[VectorStoreSearchResult]:
        if query.embedding is None:
            raise ValueError("VectorStoreQuery.embedding is required for vector search.")

        scored_records: list[tuple[float, VectorStoreRecord]] = []

        for record in self._records.values():
            if record.embedding is None:
                continue

            score = cosine_similarity(query.embedding, record.embedding)
            scored_records.append((score, record))

        scored_records.sort(key=lambda item: item[0], reverse=True)

        return [
            VectorStoreSearchResult(
                chunk_id=record.chunk_id,
                document_id=record.document_id,
                content=record.content,
                score=score,
                metadata=record.metadata,
            )
            for score, record in scored_records[: query.top_k]
        ]

    def count(self) -> int:
        return len(self._records)

    def clear(self) -> None:
        self._records.clear()


class PlaceholderVectorStore:
    async def upsert_chunks(self, records: list[VectorStoreRecord]) -> None:
        # TODO: Manually implement pgvector writes after embeddings are available.
        raise NotImplementedError("Manual vector store writes are not implemented yet.")

    async def search(self, query: VectorStoreQuery) -> list[VectorStoreSearchResult]:
        # TODO: Manually implement pgvector similarity search.
        raise NotImplementedError("Manual vector search is not implemented yet.")


def cosine_similarity(a: list[float], b: list[float]) -> float:
    """
    Calculate cosine similarity between two vectors.

    Result range:
    - close to 1.0: very similar direction
    - close to 0.0: unrelated direction
    - close to -1.0: opposite direction
    """

    if len(a) != len(b):
        raise ValueError(f"Vector dimensions do not match: {len(a)} != {len(b)}")

    dot_product = sum(x * y for x, y in zip(a, b, strict=True))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))

    if norm_a == 0 or norm_b == 0:
        return 0.0

    return dot_product / (norm_a * norm_b)